using System.Text.Json.Serialization;
using MiniInflux.Net10.Query;
using MiniInflux.Net10.Storage;

[JsonSerializable(typeof(QueryResponse))]
[JsonSerializable(typeof(QueryDebugResponse))]
[JsonSerializable(typeof(QueryResult))]
[JsonSerializable(typeof(QuerySeries))]
[JsonSerializable(typeof(ErrorResponse))]
[JsonSerializable(typeof(AdminMessage))]
[JsonSerializable(typeof(BenchmarkSnapshot))]
[JsonSerializable(typeof(HealthResponse))]
[JsonSerializable(typeof(BenchmarkRunResult))]
[JsonSerializable(typeof(BenchmarkPhaseTimings))]
[JsonSerializable(typeof(CodecComparisonBenchmark))]
[JsonSerializable(typeof(CodecBenchmarkResult))]
[JsonSerializable(typeof(FloatWorkloadBenchmark))]
[JsonSerializable(typeof(FloatStrategyBenchmarkResult))]
[JsonSerializable(typeof(BackupMetadata))]
[JsonSerializable(typeof(BackupFileEntry))]
[JsonSerializable(typeof(CliInspectSegmentResult))]
[JsonSerializable(typeof(CliInspectWalResult))]
[JsonSerializable(typeof(CliInspectManifestResult))]
[JsonSerializable(typeof(CliInspectSchemaResult))]
[JsonSerializable(typeof(CliInspectTombstoneResult))]
[JsonSerializable(typeof(CliValidateDataDirResult))]
[JsonSerializable(typeof(CliRepairResult))]
[JsonSerializable(typeof(CliCompactResult))]
[JsonSerializable(typeof(CliBackupCreateResult))]
[JsonSerializable(typeof(CliBackupVerifyResult))]
[JsonSerializable(typeof(CliRestoreResult))]
[JsonSerializable(typeof(RetentionPolicyInfo))]
[JsonSerializable(typeof(DebugStats))]
[JsonSerializable(typeof(ContinuousQueryMetrics))]
[JsonSerializable(typeof(List<ContinuousQueryMetrics>))]
[JsonSerializable(typeof(AdminSessionResponse))]
[JsonSerializable(typeof(AdminOverviewResponse))]
[JsonSerializable(typeof(AdminDatabaseSummary))]
[JsonSerializable(typeof(List<AdminDatabaseSummary>))]
[JsonSerializable(typeof(AdminRetentionPolicySummary))]
[JsonSerializable(typeof(List<AdminRetentionPolicySummary>))]
[JsonSerializable(typeof(AdminContinuousQuerySummary))]
[JsonSerializable(typeof(List<AdminContinuousQuerySummary>))]
[JsonSerializable(typeof(MaintenanceResult))]
[JsonSerializable(typeof(BackupPathRequest))]
[JsonSerializable(typeof(Dictionary<string, int>))]
[JsonSerializable(typeof(Dictionary<string, long>))]
internal partial class AppJsonContext : JsonSerializerContext { }
