reporting-disabled = true

[meta]
  dir = "D:/workingfold/MiniInflux/.benchmarks/influxdb179/meta"

[data]
  dir = "D:/workingfold/MiniInflux/.benchmarks/influxdb179/data"
  wal-dir = "D:/workingfold/MiniInflux/.benchmarks/influxdb179/wal"
  series-id-set-cache-size = 100

[http]
  enabled = true
  bind-address = "127.0.0.1:18087"
  auth-enabled = false
  log-enabled = false
  write-tracing = false
  pprof-enabled = false
  ping-auth-enabled = false

[logging]
  level = "error"
