using MiniInflux.Net10.Model;
namespace MiniInflux.Net10.Storage;
public static class CompressionCodec
{
    public static byte[] EncodeTimestamps(IReadOnlyList<long> ts){using var ms=new MemoryStream(); Varint.WriteUInt64(ms,(ulong)ts.Count); if(ts.Count==0)return ms.ToArray(); Varint.WriteUInt64(ms,Varint.ZigZag(ts[0])); long prev=ts[0],pd=0; for(int i=1;i<ts.Count;i++){var d=ts[i]-prev; Varint.WriteUInt64(ms,Varint.ZigZag(d-pd)); prev=ts[i]; pd=d;} return ms.ToArray();}
    public static List<long> DecodeTimestamps(byte[] data){using var ms=new MemoryStream(data); int n=(int)Varint.ReadUInt64(ms); var r=new List<long>(n); if(n==0)return r; var first=Varint.UnZigZag(Varint.ReadUInt64(ms)); r.Add(first); long prev=first,pd=0; for(int i=1;i<n;i++){var dod=Varint.UnZigZag(Varint.ReadUInt64(ms)); var d=pd+dod; var t=prev+d; r.Add(t); prev=t; pd=d;} return r;}
    public static byte[] EncodeValues(FieldKind k,IReadOnlyList<FieldValue> vals)=>k switch{FieldKind.Float=>EncodeDoubles(vals),FieldKind.Integer=>EncodeInts(vals),FieldKind.Boolean=>EncodeBools(vals),FieldKind.String=>EncodeStrings(vals),_=>[]};
    public static List<FieldValue> DecodeValues(FieldKind k,byte[] data)=>k switch{FieldKind.Float=>DecodeDoubles(data),FieldKind.Integer=>DecodeInts(data),FieldKind.Boolean=>DecodeBools(data),FieldKind.String=>DecodeStrings(data),_=>[]};
    static byte[] EncodeDoubles(IReadOnlyList<FieldValue> vals){using var ms=new MemoryStream(); Varint.WriteUInt64(ms,(ulong)vals.Count); ulong prev=0; foreach(var v in vals){ulong bits=(ulong)BitConverter.DoubleToInt64Bits(v.Float); Varint.WriteUInt64(ms,bits^prev); prev=bits;} return ms.ToArray();}
    static List<FieldValue> DecodeDoubles(byte[] data){using var ms=new MemoryStream(data); int n=(int)Varint.ReadUInt64(ms); var r=new List<FieldValue>(n); ulong prev=0; for(int i=0;i<n;i++){ulong bits=Varint.ReadUInt64(ms)^prev; r.Add(FieldValue.FromDouble(BitConverter.Int64BitsToDouble((long)bits))); prev=bits;} return r;}
    static byte[] EncodeInts(IReadOnlyList<FieldValue> vals){using var ms=new MemoryStream(); Varint.WriteUInt64(ms,(ulong)vals.Count); long prev=0; foreach(var v in vals){Varint.WriteUInt64(ms,Varint.ZigZag(v.Integer-prev)); prev=v.Integer;} return ms.ToArray();}
    static List<FieldValue> DecodeInts(byte[] data){using var ms=new MemoryStream(data); int n=(int)Varint.ReadUInt64(ms); var r=new List<FieldValue>(n); long prev=0; for(int i=0;i<n;i++){prev+=Varint.UnZigZag(Varint.ReadUInt64(ms)); r.Add(FieldValue.FromInteger(prev));} return r;}
    static byte[] EncodeBools(IReadOnlyList<FieldValue> vals){using var ms=new MemoryStream(); Varint.WriteUInt64(ms,(ulong)vals.Count); byte cur=0; int bit=0; foreach(var v in vals){if(v.Boolean)cur|=(byte)(1<<bit); if(++bit==8){ms.WriteByte(cur);cur=0;bit=0;}} if(bit>0)ms.WriteByte(cur); return ms.ToArray();}
    static List<FieldValue> DecodeBools(byte[] data){using var ms=new MemoryStream(data); int n=(int)Varint.ReadUInt64(ms); var payload=new byte[ms.Length-ms.Position]; ms.Read(payload); var r=new List<FieldValue>(n); for(int i=0;i<n;i++){r.Add(FieldValue.FromBoolean(((payload[i/8]>>(i%8))&1)==1));} return r;}
    static byte[] EncodeStrings(IReadOnlyList<FieldValue> vals){using var ms=new MemoryStream(); Varint.WriteUInt64(ms,(ulong)vals.Count); var dict=new Dictionary<string,int>(StringComparer.Ordinal); var arr=new List<string>(); foreach(var v in vals){var s=v.String??""; if(!dict.ContainsKey(s)){dict[s]=arr.Count; arr.Add(s);}} Varint.WriteUInt64(ms,(ulong)arr.Count); foreach(var s in arr){var b=System.Text.Encoding.UTF8.GetBytes(s); Varint.WriteUInt64(ms,(ulong)b.Length); ms.Write(b);} foreach(var v in vals)Varint.WriteUInt64(ms,(ulong)dict[v.String??""]); return ms.ToArray();}
    static List<FieldValue> DecodeStrings(byte[] data){using var ms=new MemoryStream(data); int n=(int)Varint.ReadUInt64(ms), dc=(int)Varint.ReadUInt64(ms); var dict=new string[dc]; for(int i=0;i<dc;i++){int len=(int)Varint.ReadUInt64(ms); var b=new byte[len]; ms.Read(b); dict[i]=System.Text.Encoding.UTF8.GetString(b);} var r=new List<FieldValue>(n); for(int i=0;i<n;i++)r.Add(FieldValue.FromString(dict[(int)Varint.ReadUInt64(ms)])); return r;}
}
