using System.Text.Json.Serialization;
using MiniInflux.Net10.Query;
using MiniInflux.Net10.Storage;

[JsonSerializable(typeof(QueryResponse))]
[JsonSerializable(typeof(QueryDebugResponse))]
[JsonSerializable(typeof(QueryResult))]
[JsonSerializable(typeof(QuerySeries))]
[JsonSerializable(typeof(ErrorResponse))]
[JsonSerializable(typeof(V2ErrorResponse))]
[JsonSerializable(typeof(AdminMessage))]
[JsonSerializable(typeof(BenchmarkSnapshot))]
[JsonSerializable(typeof(HealthResponse))]
[JsonSerializable(typeof(RetentionPolicyInfo))]
[JsonSerializable(typeof(DebugStats))]
[JsonSerializable(typeof(ContinuousQueryMetrics))]
[JsonSerializable(typeof(List<ContinuousQueryMetrics>))]
[JsonSerializable(typeof(AdminSessionResponse))]
[JsonSerializable(typeof(AdminOverviewResponse))]
[JsonSerializable(typeof(AdminDatabaseSummary))]
[JsonSerializable(typeof(List<AdminDatabaseSummary>))]
[JsonSerializable(typeof(AdminRetentionPolicySummary))]
[JsonSerializable(typeof(List<AdminRetentionPolicySummary>))]
[JsonSerializable(typeof(AdminContinuousQuerySummary))]
[JsonSerializable(typeof(List<AdminContinuousQuerySummary>))]
[JsonSerializable(typeof(MaintenanceResult))]
[JsonSerializable(typeof(CacheStatsResponse))]
[JsonSerializable(typeof(BackupPathRequest))]
[JsonSerializable(typeof(CreateTokenRequest))]
[JsonSerializable(typeof(TokenResponse))]
[JsonSerializable(typeof(List<TokenResponse>))]
[JsonSerializable(typeof(V3QueryRequest))]
[JsonSerializable(typeof(Dictionary<string, System.Text.Json.JsonElement>))]
[JsonSerializable(typeof(Dictionary<string, int>))]
[JsonSerializable(typeof(Dictionary<string, long>))]
internal partial class AppJsonContext : JsonSerializerContext { }
